- hosts: all
  become: yes
  tasks: 
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/ubuntu/ansible-april-2024/Homework4/.
      dest: /tmp
      owner: tim
      group: devops
      mode: '0755' 