- hosts: all
  become: yes
  tasks:
  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: [apache2, tree]
      state: present
      update_cache: yes
    notify: restart apache

  handlers: #(used as a place holder, if 1st task (aka apache2 and tree are installed) is executed then the handler won't work, if 1st task is changed, the handler will be executed)
  - name: restart apache
    service: 
      name: apache2
      state: restarted
