- hosts: all
  vars: 
    pachages:
      - apache2
      - tree
      - unzip
  become: yes
  tasks:
  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    register: hello  #(used for trouble shooting or rebooting a certain task that showded error) (basically creating an entire variable for the task above)
    ignore_errors: yes
  - debug: msg={{ hello }}